### PR TITLE
Fix unit tests

### PR DESCRIPTION
**Pull request by csrakowski**
The parameters to the method `Assert.Equal(expected, actual)` were passed in the other way around.
With this pull request I have flipped their order.

### CODE REVIEW

**Comment by csrakowski** [comment]
Hi @dvsekhvalnov,
In this PR I only did the cleanups for the netcore3.1/net5 UnitTests project.
If you agree with these changes, I can do the same to the other two.

**Comment by dvsekhvalnov** [comment]
Hey @csrakowski , yeah it looks ok in general. 
The thing is i have a lot of changes in JWK branch: https://github.com/dvsekhvalnov/jose-jwt/tree/issue_10_jwk_support

So, i'd refrain from merging until JWK released. Just don't want to deal with unit tests conflicts.

**Comment by csrakowski** [comment]
Yeah, merge conflicts on their own are bad enough, but especially ones in the UnitTests.
I'll rebase this branch to the current master, and will do that again when  JWK has been merged.

**Comment by dvsekhvalnov** [comment]
Thanks ! I'll ping you here when all ready to try again.

**Comment by csrakowski** [comment]
Hey @dvsekhvalnov,
I saw the update to 4.0 come by, and remembered I had these PRs outstanding.

The unit test errors on the .NET 5.0 build are related to invalid certificate usage/password. Since the same failures exist in the master branch, I have not looked to much into those.

**Comment by dvsekhvalnov** [comment]
Hi @csrakowski , 

it looks good to me in general. But i have a question regarding `SkippableFact`. Is purpose to make tests run on `Ubuntu` targets?

**Comment by csrakowski** [comment]
Hi @dvsekhvalnov,

Yes, it is a "cheat" sort of, to allow the specific unit tests to be skipped with a specific message.
This way you get a passing build/test run, instead of getting exceptions from inside the .NET Cryptography area saying that it requires Windows to run.

If in the future we, or the .NET team, want to make it work on Ubuntu, then we can simply change the specific tests back to "normal" `Fact`s and/or just comment out the specific `if` statements in the test.

**Comment by dvsekhvalnov** [comment]
Yeah, though my doubts are - is it make sense to hide then? When something failing we know it's still not supported on Linux .

**Comment by csrakowski** [comment]
That is indeed a matter of opinion.
My personal one is that "an error is something that you do not expect", so if the Unit Tests fail then there is something that has stopped working since the latest check in. 
Eg. in the Ubuntu .NET 5 build, there is now that error with the certificate, that is not failing in other builds. This would not be as visible if the build having errors is "normal", because the CNG tests all fail on Ubuntu anyway.

Also, these tests are not completely hidden, as xUnit does mention they are Skipped.
```
[xUnit.net 00:00:00.75]     UnitTests.JwkTest.NewEccCng_Private_P521 [SKIP]
  Skipped UnitTests.JwkTest.NewEccCng_Private_P521 [1 ms]
...
Failed!  - Failed:     2, Passed:   323, Skipped:    41, Total:   366, Duration: 7 s - /home/runner/work/jose-jwt/jose-jwt/UnitTests/bin/Debug/net50/UnitTests.dll (net5.0)
```

**Comment by dvsekhvalnov** [comment]
That's fair too. Okay, let's try and see how it gonna work :)

**Pull request merged**
