### PR TITLE
Expose CEK for encrypt/decrypt

### PR DESCRIPTION
**Pull request by dhjf**
Usecase: Use the JWE to also exchange a symmetric key (the CEK).

### CODE REVIEW

**Comment by dvsekhvalnov** [comment]
Hi @dhjf , can you elaborate little bit about use-case?

**Comment by dhjf** [comment]
Hi. Sure :-)

I want to send a JWE with RSA to my backend using the backends public key. Meanwhile I want to save the CEK used for that JWE. My backend then decrypts the CEK and the content and uses the CEK to encrypt the response. When I receive the response, I will be able to decrypt the response using the saved CEK. The CEK can now also be used to secure communication with the backend for subsequent requests. You can think of it as a Diffie–Hellman key exchange with JWE.

**Comment by dvsekhvalnov** [comment]
So, what prevents you to do it without exporting CEK?

1. Generate symmetric session key (or use Deffie-Hellman agreement). Negotiate with backend. You can use JWT to carry encrypted negotiation.

2. Use negotiated session key

**Comment by dhjf** [comment]
I simply want to use JWE for the negotiation (it integrates nicely with my solution). This also gives me a simple solution to communicate a secure message during the negotiation, so a one-off request is only a single round trip.

**Comment by dhjf** [comment]
Fair enough :)

**Comment by dvsekhvalnov** [comment]
Hey @dhjf , sorry took so long.  

Talked to people and consensus is: nobody 100% sure it's safe enough to reuse CEK more than once, though i can't give you exact use-cases against. Without 100% confidence i'd prefer not to merge pull request to avoid possible vector of vulnerabilities that i don't event understand enough.

General recommendation will be move your session key negotiation to your application layer rather than library itself. At least it will be more clear implementation.

And thank you for your effort.

**Pull request closed without merging**
