### PR TITLE
Adds Net Standard 2.0 support

### PR DESCRIPTION
**Pull request by dalexsoto**
I created this Net Standard 2.0 project in order to use it with a Xamarin.iOS project, unsure if you are actually interested in getting this in :).

I took `NET461` as baseline and started working from there, I used `UnitTestsNet46` as the base of `UnitTestsNetCore` and I have 173 test passing and 21 Skipped.

I would delegate to someone with more crypto experience than me to double check the skipped tests just to make sure they are right (in the sense of being skipped) some of them make sense like the `ECDH` because that is not available in Net Standard.

Also, I did not touch the Nuget generation because then I would force you to use VS 2017 and not sure you want that at all.

### CODE REVIEW

**Comment by dvsekhvalnov** [comment]
Hi @dalexsoto ,

thanks for contribution!

Couple questions:
  1. it looks no code changes, just adjust conditional compilation?
  2. unit tests seems to be just copy of `UnitTests` subproject (those are .netcore 1 unit tests)?

**Comment by dalexsoto** [comment]
Yes to both, no code changes and just conditional compilation and the unit tests are just a copy of the Net46 but in a Net Core xunit project.

**Comment by dvsekhvalnov** [comment]
Ok, looks good. Can you submit merge request to other branch than `master` ? 
Will need some time to set .netcore2 and cross test everything, e.t.c.

**Comment by dalexsoto** [comment]
You would need to create such branch (off master I guess?) in order for me to point my pr to it, I wish github had this propose new branch feature from PR.

**Comment by dvsekhvalnov** [comment]
Ah, yes, github...

Here we go: use `netcore20` branch.

**Comment by dalexsoto** [comment]
Closed in favour of PR #80

**Pull request closed without merging**
