### PR TITLE
Fixed code analyzer warnings

### PR DESCRIPTION
**Pull request by csrakowski**
I have fixed several code analyzer warnings, including:

- Make classes static where possible
- Make fields `readonly` where possible
- Use switch statements/expressions instead of if/else logic
- Removed trailing whitespace

Apologies for the big diff size, as I think I touched almost every single file with this PR. 😅

### CODE REVIEW

**Comment by csrakowski** [comment]
Hi @dvsekhvalnov,
Since you mentioned big work being done in the JWK branch, I recon you are also not looking for general code cleanups right now.

**Comment by csrakowski** [comment]
Hey @dvsekhvalnov,
This PR has also been updated with the latest master changes.

**Comment by dvsekhvalnov** [comment]
hey, yeah give me some time to review those.

**Comment by dvsekhvalnov** [comment]
Looks fine after spending 2h with it :) I need to try to build it locally to see if any issues on earlier .net solution. But besides that looks good.

**Comment by dvsekhvalnov** [comment]
Thank for taking care of it @csrakowski !

**Comment by csrakowski** [comment]
You're welcome.
And thank you for making the library! :-)

**Pull request merged**
