### PR TITLE
added overloads for Decode that verifies algorithm and encryption types

### PR DESCRIPTION
**Pull request by oscarlinderholm**
Adds more validation before decoding a token as discussed at: https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/

### CODE REVIEW

**Comment by dvsekhvalnov** [comment]
Hi @oscarlinderholm,

what you pull request is adding? jose-jwt is not vulnerable to the issue described in the link you posted and never was.

**Comment by oscarlinderholm** [comment]
Hi,

I realize that the current implementation isn't vulnerable to the attack described in the link. I do however think that it's a good idea to prevent the client from determining which algorithm and/or encryption method to use for validation.

It never hurts to add an extra layer of defense if possible.

**Comment by dvsekhvalnov** [comment]
That's right point. But you don't need to change interfaces to achieve this. Have you seen: https://github.com/dvsekhvalnov/jose-jwt#two-phase-validation  ?

You can read headers before processing tokens via: `var headers = Jose.JWT.Headers(token);`

Better extensions to interface will be to overload  to accept pre-process lambda in Jose.JWT.Decode(..), that will receive headers and unprocessed payload to make decision before further actual processing.

**Comment by oscarlinderholm** [comment]
That would also be a solution, but I think that it would be better to have this by default so that users of the library don't have to re-implement this.

It will not break any existing use of the library since the methods I added are overloaded versions of the Decode method.

**Comment by dvsekhvalnov** [comment]
@oscarlinderholm, ok sounds reasonable. Would you mind add docs to README.md? Let's say section called 'Strict validation' may be next to 'Two-Phase validation'.

**Comment by oscarlinderholm** [comment]
No problem, I have pushed a new section to the README.md now

**Comment by dvsekhvalnov** [comment]
Thanks.

**Comment by dvsekhvalnov** [comment]
I'll republish to nuget soon.

**Comment by oscarlinderholm** [comment]
Perfect, thank you.

**Comment by dvsekhvalnov** [comment]
v1.9.2 published to nuget.org

**Pull request merged**
